---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base:9.2.0
  amd64: ghcr.io/hassio-addons/debian-base:9.2.0
labels:
  org.opencontainers.image.title: "Channels DVR Server"
  org.opencontainers.image.description: "Manage and record live TV with Channels DVR Server"
  org.opencontainers.image.source: "https://github.com/mekenthompson/hass-addon-channels-dvr"
  org.opencontainers.image.licenses: "MIT"
  org.opencontainers.image.authors: "Ken Thompson"
  org.opencontainers.image.vendor: "Ken Thompson"

